server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: postgres
    hikari:
      schema: task_schema

  liquibase:
    change-log: classpath:db.change-log/db.changelog-master.xml
    enabled: true
    drop-first: false